# Generated by Django 4.2.18 on 2025-01-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="customer",),
        migrations.RemoveField(model_name="orderitem", name="order",),
        migrations.RemoveField(model_name="orderitem", name="product",),
        migrations.RemoveField(model_name="shippingaddress", name="customer",),
        migrations.RemoveField(model_name="shippingaddress", name="order",),
        migrations.DeleteModel(name="Customer",),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="OrderItem",),
        migrations.DeleteModel(name="ShippingAddress",),
    ]
